name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: snapshot
      - uses: actions/checkout@v2
      - name: Run tests
        run: './t/test-config'
